### ISSUE TITLE
您好，反映下conference paper中ICCV2021文章链接存在的问题。

### ISSUE THREAD

**Issue by Love666sJane** [wangdongdut/Online-Visual-Tracking-SOTA#4]
《Box-Aware Feature Enhancement for Single Object Tracking on Point Clouds》链接到其他的了paper。

**Comment by wangdongdut** [comment]
> 《Box-Aware Feature Enhancement for Single Object Tracking on Point Clouds》链接到其他的了paper。

It' ok. Sorry for that.
